@startuml
actor ユーザ
boundary CUIインタフェース
control チェックアウト処理
entity 予約

ユーザ -> CUIインタフェース: 予約番号を入力
CUIインタフェース -> チェックアウト処理: 入力された予約番号を送信
チェックアウト処理 -> チェックアウト処理: 予約番号を検証
alt 予約番号が有効
    チェックアウト処理 -> 予約: 予約をキャンセル
    予約-> チェックアウト処理: キャンセル完了の通知
    チェックアウト処理 -> CUIインタフェース: キャンセル完了の通知
    CUIインタフェース -> ユーザ: キャンセル完了の通知
else 予約番号が無効
    チェックアウト処理 -> CUIインタフェース: エラーメッセージを送信
    CUIインタフェース -> ユーザ: エラーメッセージを表示
end

@enduml