@startuml
class User
User : Int id
User : String name

class Clerk
Clerk : String name

class Reserve
Reserve : User user
Reserve : Room room
Reserve : Clerk clerk
Reserve : Payment payment
Reserve : Date checkInDate
Reserve : Date checkOutDate
Reserve : Date reserveDate

class Room
Room : Int roomNo
Room : Int price
Room : Date[] schedule

abstract class Payment
Payment : String type
Payment : Int amount
Payment : Bool isPaid

class Cash
Cash : String type
Cash : Int amount
Cash : Bool isPaid

class Card
Card : String type
Card : Int amount
Card : Bool isPaid

class Hotel
Hotel : String name
Hotel : Room[] rooms
Hotel : Clerk[] clerks
Hotel : Reserves[] reserves

Hotel *-- "1..*" Room
Hotel *-- "1..*" Clerk
Hotel o-- "1..*" Reserve
Reserve -- "1..1" User
Reserve -- "1..1" Room
Reserve -- "1..1" Payment
Reserve -- "1..1" Clerk
Payment <|-- "1..1" Cash
Payment <|-- "1..1" Card
@enduml